### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by pennybuster** [rexcontrols/REXexamples#1]
Hi. I'm planning to develop a home automation solution next year and REX Control System looks very promising. The UniPi looks interesting too.
I suggest you implement a notification module for the HMI web component for sending alerts via email and SMS, and posting content on Facebook and Twitter. That would make your product complete. Even those who are looking to develop industrial automation solutions would benefit from the alerting feature. I really think it's a MUST even if you increase the price.
Also, I recommend choosing Nginx instead of Lighttpd as the web server. Lighttpd still has problems with memory leaks and CPU consumpson as of 2015, or so I've been told. The experts say Nginx is the most stable, efficient and secure web server. Thank you.

**Comment by rexcontrols** [comment]
Hi pennybuster, thanks for your message. Please find my reply in our forum at 
http://www.rexcontrols.com/forum/viewtopic.php?id=8
If you have any additional questions or sugestions, I'll be happy to meet you there!
